# Editor: https://editor.swagger.io/

openapi: 3.0.3
info:
  version: 0.1.0
  title: "@ccc/service"
servers:
  - url: https://localhost:8000
    description: Local development server
    
paths:
  /auth/login:
    post:
      description: User login      
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCredentials'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
          
  /auth/register:
    post:
      description: User registration      
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCredentials'
      responses:
        '201':
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '403':
          description: Credentials are not valid
        '422':
          description: User already exists
          
  /cookies:
    get:
      description: Get cookies for current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cookies'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
          
  /cookies/{operator}:
    patch:
      description: Increment or decrement the cookie counter
      security:
        - bearerAuth: []
      parameters:
        - in: path
          description: Operation to be executed
          name: operator
          required: true
          schema: 
            type: string
            enum:
              - increment
              - decrement
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cookies'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: No rights to increment
        
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      
  schemas:
    AuthCredentials:
      type: object
      properties:
        name:
          description: Submitted user name
          type: string
        password:
          description: Submitted user password
          type: string
      required:
        - name
        - password
        
    AuthResponse:
      type: object
      properties:
        token:
          description: Bearer token for further authentication
          type: string
        user:
          $ref: '#/components/schemas/User'
      required:
        - token
        - user
    
    User:
      description: Information about a user
      type: object
      properties:
        id:
          description: UID of the user
          type: string
        name: 
          description: Name of the user
          type: string
        role:
          description: Role of the user
          type: string
          enum:
            - admin
            - user
      required:
        - id
        - name
        - role

    Cookies:
      type: object
      properties:
        amount:
          description: Amount of cookies
          type: number
